### ISSUE TITLE
Extend The Wire plugin instead?

### ISSUE THREAD

**Issue by rjcalifornia** [physcocode/the-wire-pro#1]
Hi there!

Nice work with The Wire Pro. However, if the user upgrades the site this plugin will be "removed". May I suggest you to extend it instead? You can take a look at this plugin I made and check out how to properly extend views and functions:

https://github.com/rjcalifornia/super-river

**Comment by physcocode** [comment]
@rjcalifornia I was thinking about same ! The next task on my check list is to extend the wire instead to replacing it , that will also make compatibility with plugins like "the wire tools" possible ! . Thank you for the reference plugin will work on the same :)

**Comment by physcocode** [comment]
@rjcalifornia this has been fixed in the new release , thank you for your contribution :)
