### ISSUE TITLE
I was able to install plugin but I do not get emoji icons when posting

### ISSUE THREAD

**Issue by smam2021** [physcocode/the-wire-pro#10]
I was able to install plugin but I do not get emoji icons when posting. I also do not see the image of a link if I post it. The image of the website I post.

**Comment by ipranjal** [comment]
can you share a example screenshot ?

**Comment by smam2021** [comment]
Hi sorry I just read automatically convert text like :) into emoji. I thought there would be a drop down where you could choose one.

I do want to know how when you place a link in a post how can that link can bring up a picture of the website?

**Comment by ipranjal** [comment]
wen you paste a link it will automatically try to fetch content using oembed I have test it with YouTube and Vemo

**Comment by smam2021** [comment]
It does not fetch the website for my setup. I just post a link and thats all that shows up.

**Comment by ipranjal** [comment]
@smam2021  if you have downloaded source form GitHub you would have to manually run composer install , its better you directly download the release version from elgg website :)

**Comment by smam2021** [comment]
What I mean is when I post a website in a post it will not goto the website and fetch the content and display the image of the website on the post.
