### ISSUE TITLE
Allow wire replies/comments to fold/unfold

### ISSUE THREAD

**Issue by staion16** [physcocode/the-wire-pro#2]
I think I already posted this suggestion on your plugin page on Elgg website, but would be great to allow thewire post replies/comments to fold and unfold in some whay, because as of now, they fill in too much space on feed pages. I don't mind them opened on thread pages. Maybe create a JS link or button.

**Comment by physcocode** [comment]
@staion16 I am planning to rework the comment part to be more inline with the new elgg comment system . Will address this in next release

**Comment by staion16** [comment]
Thanks for considering it, and would also be nice if you could add likes as well.

**Comment by physcocode** [comment]
@staion16 this issue is fixed in the latest release :) thank you for your suggestions
