### ISSUE TITLE
This plugin is invaild,plugin directory must be renamed to match id in its manifest

### ISSUE THREAD

**Issue by smam2021** [physcocode/the-wire-pro#9]
This plugin is invaild,plugin directory must be renamed to match id in its manifest
![thewire](https://user-images.githubusercontent.com/90880679/133711378-5d2bc501-bc60-464e-a8cc-399f055b7a6d.JPG)

I have created the folder but it still shows this error.

**Comment by ipranjal** [comment]
did you download from GitHub ? please download it from elgg website https://elgg.org/plugins/3079200 you will get the correct directory name or you can just rename directory from "The-wire-pro" to just "thewirepro"
